### ISSUE TITLE
불필요한 li tag

### ISSUE THREAD

**Issue by gem1n1-youngjae** [wei756/Everywak#45]
https://github.com/wei756/Everywak/blob/a7a0837c280b862281d2269323b7b14e5cc6b2ec/src/modules/waktoon/WaktoonChartItem.jsx#L63

@wei756 코드를 구경 하던 도중 불필요한 li 태그를 발견했습니다!

**Comment by wei756** [comment]
차트 리스트에 슬라이드 구현하려고 li태그를 씌웠었는데 커밋 분리하면서 실수했던 거 같습니다
해당 사항 반영된 코드 커밋했습니다 피드백주셔서 감사합니다!
